version: '3'
services:
  webserver:
    build:
      context: ./bin/nginx
    container_name: '${PROJECT_NAME}-webserver-nginx'
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    ports:
      - '${UNSECURE_HOST_PORT}:80'
      - '${SECURE_HOST_PORT}:443'
    volumes:
      - '${WEBROOT}:/usr/share/nginx/html'
      - '${VHOST_DIR}:/etc/nginx/conf.d'
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./bin/php-fpm
      args:
        packagist_user_token: '${PACKAGIST_USER_TOKEN}'
    container_name: '${PROJECT_NAME}-php-fpm'
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    volumes:
      - '${WEBROOT}:/usr/share/nginx/html'
      - './config/php-fpm/php.ini:/usr/local/etc/php/php.ini'
  redis:
    image: redis:latest
    container_name: '${PROJECT_NAME}-redis'
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./bin/redis/redis.conf:/usr/local/etc/redis/redis.conf
  postgresql:
    image: postgresql:latest
    container_name: '${PROJECT_NAME}-postgresql'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_POSTGRESQL_PORT}:5432"
    volumes: 
      - ./data/postgresql:/var/lib/postgresql/data
      - ./logs/postgresql:/var/log/postgresql
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}